COLUMNS :
  Age : int16
  Nationality : object
  Club : object
  Contract Valid Until : float64
  Height : Float32
  Weight : Float32
  Release Clause : Float32
  month : Float32
  year : Float32
TARGET_COLUMN :
  name : Overall


