data_ingestion: 
  source_URL : bryanb/fifa-player-stats-database
  local_data_file : C:/Users/HP/.cache/kagglehub/datasets/bryanb/fifa-player-stats-database/versions/35
data_transformation:
  raw_data : data\raw\35\FIFA23_official_data.csv